config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/dashboard'
  get 'posts/create'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true

    before_save :censor_word
    def censor_word
        self.content = self.content.gsub('spoiler', '')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard

  def index
    @posts = Post.order(created_at: :desc)
  end

  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end

  def dashboard
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
  
</html>

app/views/posts/create.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <div>
            <%= link_to "Ir a inicio", posts_index_path, class:"btn btn-primary mr-5" %>
        </div>

    </div>
<% else %>
    <h1 class="mt-4 mb-4">Publicación exitosa</h1>
    <span>
        <%= link_to "Ir a Inicio", posts_index_path, class:"btn btn-primary mr-5" %>
        <%= link_to "Ir a Dashboard", posts_dashboard_path, class:"btn btn-success mr-5" %>
    </span>
<% end %>

app/views/posts/dashboard.html.erb
  <div class="text-center m-4">
    <h1>Dashboard</h1>
  </div>

<div class="container border rounded bg-light mt-4">
  <form id="create_posts" method="get" action="/posts/create">
  <h2 class="mt-4 mb-4">Crear Post</h2><hr>
    <div class="mt-3"> 
      <h4>Titulo</h4>
      <input name="title" class="form form-control">
    </div>
    
    <div class="mt-3">
      <h4>Imagen</h4>
      <input name="image_url" class="form form-control">
    </div>
    
    <div class="mt-3">
      <h4>Contenido</h4>
      <textarea name="content" class="form form-control"></textarea>
    </div>
    
    <span class="mt-3 mb-3 d-flex flex-row-reverse">
      <input type="submit" value="Publicar post" class="btn btn-success">    
      <%= link_to "Ir a inicio", posts_index_path, class:"btn btn-primary mr-5" %>
    </span>

  </form>


</div>

app/views/posts/index.html.erb
<div  class="m-4">
    <h1 class="text-center">Inicio</h1>
</div>

<div class="container mb-5">
    <%= link_to "Dashboard", posts_dashboard_path, class:"btn btn-primary" %>
</div>

<div class="container">
    <table class="table border rounded">

        <thead class="thead-primary">
            <tr class="table-warning">
                <th>Titulo</th>
                <th>Fecha de ingreso</th>
                <th>Imagen</th>
                <th>Contenido</th>
            </tr>
        </thead>

        <% @posts.each do |post| %>
            <tr class="bg-light">
                <td><%= post.title %></td>
                <td><%= post.created_at %></td>
                <td><%= post.image_url %></td>
                <td><%= post.content %></td>
            </tr>
        <% end %>

    </table>
</div>